name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore "DeclarativePM/DeclarativePM.UI/DeclarativePM.UI.csproj"
    - name: Build
      run: dotnet build --no-restore "DeclarativePM/DeclarativePM.UI/DeclarativePM.UI.csproj"
    - name: Test
      run: dotnet test --no-build --verbosity normal "DeclarativePM/TestRunning/TestRunning.csproj"
